// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MachineLearningTest
{
    public class ModelInput
    {
        [ColumnName("White"), LoadColumn(0)]
        public bool White { get; set; }


        [ColumnName("Hue"), LoadColumn(1)]
        public float Hue { get; set; }


        [ColumnName("Saturation"), LoadColumn(2)]
        public float Saturation { get; set; }


        [ColumnName("Brightness"), LoadColumn(3)]
        public float Brightness { get; set; }


    }
}
